modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="obloch"
version="1.0.0"
displayName="Obloch"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="janis, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.obloch]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.101-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.obloch]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration